package com.github.manjunathprabhakar.moved.constants;

public enum DataFields {
    //FEATURE DATAS
    FEATURE_INDEX,
    FEATURE_NAME,
    TOTAL_SCENARIOS,
    TOTAL_PASSED_SCENARIOS,
    TOTAL_FAILED_SCENARIOS,
    TOTAL_SKIPPED_SCENARIOS,
    TOTAL_OTHERSTATUS_SCENARIOS,
    FEATURE_STATUS,

    //SCENARIO DATAS
    SCENARIO_INDEX,
    SCENARIO_NAME,
    SCENARIO_STATUS,

    //STEPS DATA
    TOTAL_STEPS,
    TOTAL_PASSED_STEPS,
    TOTAL_FAILED_STEPS,
    TOTAL_SKIPPED_STEPS,
    TOTAL_OTHERSTATUS_STEPS,

    //TAGS DATA
    TAG_NAME,

    //AUDIT DATA
    TIME_STAMP,
    DATE,
    MACHINE_NAME,
    USER_NAME

}
